require 'securerandom'

fastlane_version "1.47.0"

default_platform :ios

platform :ios do

  before_all do
    ensure_git_status_clean
  end

  desc "Runs all the tests"
  lane :test do
    scan(device: "iPhone 6s (9.2)")
  end

  desc "Submit a new Beta build to Hockey App"
  lane :beta do

    increment_build_number(build_number: number_of_commits)

    # Build
    gym(
      configuration: "Ad Hoc",
      sdk: "iphoneos9.2",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      use_legacy_build_api: true,
      export_method: "enterprise"
    )

    # Push to Hockey
    hockey(
      api_token: ENV["HOCKEY_API_TOKEN"],
      public_identifier: ENV["HOCKEY_APP_ID"],
      notify: '0',
      status: '2',
      notes: last_git_commit[:message] + "\n(Uploaded automatically via fastlane)"
    )

  end
end

